"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { apiRequest } from "../services/api";
import { useAuth } from "../hooks/useAuth";

type Summary = { activeProjects: number; openTasks: number; overdueTasks: number; upcomingDeadlines: number; completedTasks: number; activeEmployees: number };
type AttentionItem = { id: string; title: string; description: string; href: string; severity: "CRITICAL" | "ATTENTION" };
type ProjectHealth = { id: string; name: string; status: string; openTasks: number; completedTasks: number; overdueTasks: number; dueDate: string | null; completionPercent: number; health: "CRITICAL" | "ATTENTION" | "ON_TRACK"; href: string };
type EmployeeWorkload = { userId: string; name: string; openTasks: number; completedTasks: number; overdueTasks: number };
type CommandCenter = { summary: Summary; attentionItems: AttentionItem[]; companyHealth: "CRITICAL" | "ATTENTION_NEEDED" | "ON_TRACK"; healthExplanation: string; projectHealth: ProjectHealth[]; workload: EmployeeWorkload[]; aiInsight: string };

const metricLabels: Array<[keyof Summary, string, string]> = [
  ["activeProjects", "Active projects", "Current company projects"],
  ["openTasks", "Open tasks", "Tasks not marked done"],
  ["overdueTasks", "Overdue tasks", "Open tasks past due"],
  ["upcomingDeadlines", "Upcoming deadlines", "Within the next 7 days"],
  ["completedTasks", "Completed tasks", "Marked done"],
  ["activeEmployees", "Active employees", "Approved company members"],
];

export default function CommandCenterManager() {
  const { accessToken } = useAuth();
  const [data, setData] = useState<CommandCenter | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!accessToken) return;
    void apiRequest<CommandCenter>("/api/command-center", { token: accessToken })
      .then(setData)
      .catch(cause => setError(cause instanceof Error ? cause.message : "Unable to load Command Center."));
  }, [accessToken]);

  if (error) return <main className="mx-auto min-h-screen max-w-7xl px-4 py-10 sm:px-6"><p role="alert" className="rounded-xl border border-rose-900 bg-rose-950/40 p-4 text-sm text-rose-200">{error}</p></main>;
  if (!data) return <main className="grid min-h-screen place-items-center px-4 text-sm text-slate-400" role="status">Loading Command Center...</main>;

  return <main className="mx-auto min-h-screen max-w-7xl px-4 py-8 sm:px-6 lg:py-10">
    <header className="mb-8 flex flex-wrap items-end justify-between gap-4">
      <div><p className="page-eyebrow">Executive overview</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Command Center</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">A current view of company delivery, deadlines, and workload.</p></div>
      <Link href="/analytics" className="button-secondary">View analytics</Link>
    </header>

    <section aria-label="Company summary" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
      {metricLabels.map(([key, label, hint]) => <article key={key} className="metric-card"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-3xl font-bold tabular-nums">{data.summary[key]}</p><p className="mt-1 text-xs text-slate-500">{hint}</p></article>)}
    </section>

    <section className="mt-6 grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <article className="panel">
        <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="page-eyebrow">Priorities</p><h2 className="mt-1 text-xl font-semibold">Attention Needed</h2></div><span className={`rounded-full border px-3 py-1 text-xs font-semibold ${healthStyle(data.companyHealth)}`}>{healthLabel(data.companyHealth)}</span></div>
        <p className="mt-3 text-sm text-slate-400">{data.healthExplanation}</p>
        {data.attentionItems.length === 0 ? <p className="mt-5 rounded-xl border border-dashed border-slate-700 p-5 text-sm text-slate-400">No immediate attention items found.</p> : <ul className="mt-5 space-y-3">{data.attentionItems.map(item => <li key={item.id}><Link href={item.href} className="flex flex-col gap-2 rounded-xl border border-slate-800 bg-slate-950/40 p-4 hover:border-slate-600 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-slate-100">{item.title}</p><p className="mt-1 text-sm text-slate-400">{item.description}</p></div><span className={`w-fit rounded-full px-2.5 py-1 text-[11px] font-semibold ${item.severity === "CRITICAL" ? "bg-rose-500/10 text-rose-300" : "bg-amber-500/10 text-amber-300"}`}>{item.severity === "CRITICAL" ? "Critical" : "Upcoming"}</span></Link></li>)}</ul>}
      </article>
      <article className="panel"><p className="page-eyebrow">Authorized work insights</p><h2 className="mt-1 text-xl font-semibold">AI Executive Insight</h2><p className="mt-2 text-xs text-slate-500">Generated by the existing work insights service from current company records.</p><p aria-live="polite" className="mt-5 whitespace-pre-wrap rounded-xl border border-slate-800 bg-slate-950/60 p-4 text-sm leading-6 text-slate-300">{data.aiInsight || "No immediate attention items found."}</p><Link href="/ai-assistance" className="mt-4 inline-flex text-sm font-medium text-sky-300 hover:text-sky-200">Open Knowledge Assistant <ArrowRightIcon /></Link></article>
    </section>

    <section className="panel mt-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="page-eyebrow">Delivery</p><h2 className="mt-1 text-xl font-semibold">Project health</h2></div><Link href="/projects" className="text-sm font-medium text-sky-300 hover:text-sky-200">Open projects</Link></div>
      {data.projectHealth.length === 0 ? <Empty>No active company projects.</Empty> : <div className="mt-4 grid gap-3 lg:grid-cols-2">{data.projectHealth.map(project => <article key={project.id} className="rounded-xl border border-slate-800 bg-slate-950/35 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{project.name}</h3><p className="mt-1 text-xs text-slate-500">{project.status.replaceAll("_", " ")}{project.dueDate ? `  | Due ${project.dueDate}` : "  | No deadline"}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${projectHealthStyle(project.health)}`}>{projectHealthLabel(project.health)}</span></div><div className="mt-4 flex justify-between text-xs text-slate-400"><span>{project.openTasks} open</span><span>{project.completedTasks} completed</span><span>{project.overdueTasks} overdue</span></div><div className="mt-2 h-2 rounded-full bg-slate-800" role="progressbar" aria-label={`${project.name} task completion`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={project.completionPercent}><div className="h-2 rounded-full bg-sky-500" style={{ width: `${project.completionPercent}%` }} /></div><p className="mt-1 text-right text-xs text-slate-500">{project.completionPercent}% task completion</p><Link href={project.href} className="mt-3 inline-flex text-sm text-sky-300 hover:text-sky-200">View project workspace <ArrowRightIcon /></Link></article>)}</div>}
    </section>

    <section className="panel mt-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="page-eyebrow">Capacity</p><h2 className="mt-1 text-xl font-semibold">Workload overview</h2></div><p className="text-xs text-slate-500">Counts include tasks assigned to each active company member.</p></div>
      {data.workload.length === 0 ? <Empty>No active employees to report.</Empty> : <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><caption className="sr-only">Task workload for active company employees</caption><thead className="border-b border-slate-800 text-xs text-slate-400"><tr><th scope="col" className="pb-3 font-medium">Employee</th><th scope="col" className="pb-3 font-medium">Open tasks</th><th scope="col" className="pb-3 font-medium">Completed tasks</th><th scope="col" className="pb-3 font-medium">Overdue tasks</th></tr></thead><tbody>{data.workload.map(person => <tr key={person.userId} className="border-b border-slate-800/70 last:border-0"><th scope="row" className="py-3 font-medium">{person.name}</th><td className="py-3 tabular-nums">{person.openTasks}</td><td className="py-3 tabular-nums text-emerald-300">{person.completedTasks}</td><td className="py-3 tabular-nums text-rose-300">{person.overdueTasks}</td></tr>)}</tbody></table></div>}
    </section>
  </main>;
}

function Empty({ children }: { children: string }) { return <p className="mt-4 rounded-xl border border-dashed border-slate-700 p-5 text-sm text-slate-400">{children}</p>; }
function healthLabel(value: CommandCenter["companyHealth"]) { return value === "CRITICAL" ? "Critical" : value === "ATTENTION_NEEDED" ? "Attention needed" : "On track"; }
function healthStyle(value: CommandCenter["companyHealth"]) { return value === "CRITICAL" ? "border-rose-800 bg-rose-500/10 text-rose-300" : value === "ATTENTION_NEEDED" ? "border-amber-800 bg-amber-500/10 text-amber-300" : "border-emerald-800 bg-emerald-500/10 text-emerald-300"; }
function projectHealthLabel(value: ProjectHealth["health"]) { return value === "CRITICAL" ? "Critical" : value === "ATTENTION" ? "Attention" : "On track"; }
function projectHealthStyle(value: ProjectHealth["health"]) { return value === "CRITICAL" ? "bg-rose-500/10 text-rose-300" : value === "ATTENTION" ? "bg-amber-500/10 text-amber-300" : "bg-emerald-500/10 text-emerald-300"; }

function ArrowRightIcon() { return <svg className="ml-1 h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6" /></svg>; }
