"use client";
import { FormEvent, useState } from "react";
import { apiRequest } from "../services/api";
import { useAuth } from "../hooks/useAuth";
type Source={id:string;title:string;excerpt:string}; type Reply={answer:string;sources:Source[]};
export default function KnowledgeChat(){
 const{accessToken}=useAuth(); const[input,setInput]=useState(""); const[reply,setReply]=useState<Reply|null>(null); const[loading,setLoading]=useState(false); const[error,setError]=useState("");
 async function ask(e:FormEvent){e.preventDefault();if(loading||!input.trim()||!accessToken)return;setLoading(true);setError("");try{setReply(await apiRequest<Reply>("/api/ai/ask",{method:"POST",token:accessToken,body:{question:input}}));}catch(cause){setError(cause instanceof Error?cause.message:"Knowledge lookup failed.");}finally{setLoading(false);}}
 return <main className="mx-auto min-h-screen max-w-4xl px-4 py-10 sm:px-6 sm:py-12"><p className="text-sm font-medium text-sky-400">Company knowledge</p><h1 className="mt-1 text-3xl font-bold">AI assistant</h1><p className="mt-3 text-slate-400">Ask about company tasks, project status, deadlines, meetings, or approved documents. Work insights use records you are authorized to access.</p><section aria-busy={loading} className="mt-8 rounded-xl border border-slate-800 bg-slate-900/60 p-5">
 {reply&&<div className="mb-5 rounded-lg bg-slate-950 p-4"><p className="leading-7">{reply.answer}</p>{reply.sources.length>0&&<div className="mt-5 space-y-3"><p className="text-sm font-semibold text-sky-400">Sources</p>{reply.sources.map(s=><article key={s.id} className="rounded border border-slate-800 p-3"><p className="font-medium">{s.title}</p><p className="mt-1 text-sm text-slate-400">{s.excerpt}</p></article>)}</div>}</div>}
 {loading&&<p role="status" className="mb-4 rounded-lg border border-slate-800 bg-slate-950/60 p-4 text-sm text-slate-300">Searching authorized company knowledge...</p>}{error&&<p role="alert" className="mb-4 rounded-lg border border-rose-900 bg-rose-950/40 p-3 text-sm text-rose-200">{error}</p>}{!reply&&!loading&&!error&&<p className="mb-4 rounded-lg border border-dashed border-slate-700 p-4 text-sm text-slate-400">Your answer and its authorized sources will appear here.</p>}
 <form onSubmit={ask} className="flex flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="knowledge-question">Question</label><input id="knowledge-question" required value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about company work or approved knowledge" className="field min-w-0 flex-1"/><button type="submit" disabled={loading||!input.trim()} className="rounded-xl bg-sky-500 px-4 py-2.5 font-medium text-slate-950 hover:bg-sky-400 disabled:cursor-not-allowed disabled:opacity-60">{loading?"Searching...":"Ask"}</button></form></section></main>
}
