"use client";
import { useEffect, useState } from "react";
import type { User, UserRole } from "../types/auth";
import { apiRequest } from "../services/api";
import { useAuth } from "../hooks/useAuth";
type JoinRequest={id:string;name:string;email:string;createdAt:string};
export default function UsersManager(){const{accessToken,user:currentUser}=useAuth();const[users,setUsers]=useState<User[]>([]);const[requests,setRequests]=useState<JoinRequest[]>([]);const[error,setError]=useState("");const[saving,setSaving]=useState<string|null>(null);
 async function load(){if(!accessToken)return;try{const [people,pending]=await Promise.all([apiRequest<User[]>("/api/users",{token:accessToken}),apiRequest<JoinRequest[]>("/api/users/join-requests",{token:accessToken})]);setUsers(people);setRequests(pending);}catch(e){setError(e instanceof Error?e.message:"Unable to load company people.");}}useEffect(()=>{void load();},[accessToken]);
 async function role(user:User,next:UserRole){if(!accessToken||!user.id||user.role===next)return;setSaving(user.id);try{await apiRequest(`/api/users/${user.id}/role`,{method:"PATCH",token:accessToken,body:{role:next}});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update role.");}finally{setSaving(null);}}
 async function decide(id:string,decision:"approve"|"reject"){if(!accessToken)return;setSaving(id);try{await apiRequest(`/api/users/join-requests/${id}/${decision}`,{method:"PATCH",token:accessToken});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update request.");}finally{setSaving(null);}}
 return <main className="mx-auto min-h-screen max-w-7xl px-4 py-10 sm:px-6"><div className="mb-8"><p className="text-sm font-medium text-sky-400">Company management</p><h1 className="mt-1 text-3xl font-bold">People and access</h1><p className="mt-2 text-slate-400">Approve join requests and manage approved company members.</p></div>{error&&<p role="alert" className="mb-5 rounded-lg border border-rose-900 bg-rose-950/40 p-3 text-sm text-rose-200">{error}</p>}<section className="mb-6 rounded-xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="font-semibold">Pending join requests</h2>{requests.length===0?<p className="mt-3 text-sm text-slate-400">No pending requests.</p>:<div className="mt-3 space-y-3">{requests.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-800 p-3"><div><p className="font-medium">{r.name}</p><p className="text-sm text-slate-400">{r.email}</p></div><div className="flex gap-2"><button disabled={saving===r.id} onClick={()=>void decide(r.id,"approve")} className="rounded bg-emerald-500 px-3 py-1.5 text-sm font-medium text-slate-950">Approve</button><button disabled={saving===r.id} onClick={()=>void decide(r.id,"reject")} className="rounded border border-rose-700 px-3 py-1.5 text-sm text-rose-200">Reject</button></div></div>)}</div>}</section><section className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="mb-4 font-semibold">Approved members</h2><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-slate-800 text-slate-400"><tr><th className="pb-3">Person</th><th className="pb-3">Email</th><th className="pb-3">Role</th><th className="pb-3">Access</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-slate-800/70 last:border-0"><td className="py-4 font-medium">{u.name}{u.id===currentUser?.id&&<span className="ml-2 text-xs text-slate-500">You</span>}</td><td className="py-4 text-slate-300">{u.email}</td><td className="py-4">{u.role}</td><td className="py-4"><select value={u.role} disabled={saving===u.id} onChange={e=>void role(u,e.target.value as UserRole)} className="rounded-md border border-slate-700 bg-slate-950 px-2 py-1.5"><option value="MEMBER">Member</option><option value="ADMIN">Administrator</option></select></td></tr>)}</tbody></table></section></main>;}
