CREATE TABLE projects (
 id UUID PRIMARY KEY, name VARCHAR(160) NOT NULL, description TEXT, status VARCHAR(32) NOT NULL DEFAULT 'PLANNING', archived BOOLEAN NOT NULL DEFAULT FALSE,
 owner_id UUID NOT NULL REFERENCES users(id), due_date DATE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE project_members (project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, PRIMARY KEY(project_id,user_id));
CREATE TABLE tasks (
 id UUID PRIMARY KEY, project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, title VARCHAR(200) NOT NULL, description TEXT, status VARCHAR(32) NOT NULL DEFAULT 'TODO', priority VARCHAR(32) NOT NULL DEFAULT 'MEDIUM',
 assignee_id UUID REFERENCES users(id), creator_id UUID NOT NULL REFERENCES users(id), due_date DATE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE task_comments (id UUID PRIMARY KEY, task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, author_id UUID NOT NULL REFERENCES users(id), content TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE notifications (id UUID PRIMARY KEY, recipient_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, title VARCHAR(180) NOT NULL, body TEXT NOT NULL, type VARCHAR(40) NOT NULL, read BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE documents (id UUID PRIMARY KEY, title VARCHAR(200) NOT NULL, file_name VARCHAR(255) NOT NULL, content_type VARCHAR(120), storage_path VARCHAR(500), extracted_text TEXT, visibility VARCHAR(32) NOT NULL DEFAULT 'COMPANY', project_id UUID REFERENCES projects(id) ON DELETE SET NULL, owner_id UUID NOT NULL REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE meetings (id UUID PRIMARY KEY, title VARCHAR(200) NOT NULL, project_id UUID REFERENCES projects(id) ON DELETE SET NULL, organizer_id UUID NOT NULL REFERENCES users(id), scheduled_at TIMESTAMPTZ, transcript TEXT, summary TEXT, decisions TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE activity_logs (id UUID PRIMARY KEY, actor_id UUID REFERENCES users(id) ON DELETE SET NULL, action VARCHAR(80) NOT NULL, entity_type VARCHAR(60) NOT NULL, entity_id UUID, summary VARCHAR(500) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_projects_owner ON projects(owner_id); CREATE INDEX idx_tasks_project ON tasks(project_id); CREATE INDEX idx_tasks_assignee ON tasks(assignee_id); CREATE INDEX idx_notifications_recipient ON notifications(recipient_id, read); CREATE INDEX idx_activity_created ON activity_logs(created_at DESC);
