package com.enterpriseflow.service;
import com.enterpriseflow.entity.*; import com.enterpriseflow.knowledge.dto.*; import com.enterpriseflow.repository.*;
import org.springframework.beans.factory.annotation.Value; import org.springframework.core.io.FileSystemResource; import org.springframework.core.io.Resource; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile;
import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.time.*; import java.util.*;
@Service public class KnowledgeService {
 private final DocumentRepository documents; private final MeetingRepository meetings; private final MeetingActionItemRepository actionItems; private final UserRepository users; private final ProjectRepository projects; private final TaskRepository tasks; private final ActivityLogRepository activity; private final Path storageDirectory; private final WorkInsightsService workInsights;
 public KnowledgeService(DocumentRepository d,MeetingRepository m,MeetingActionItemRepository ai,UserRepository u,ProjectRepository p,TaskRepository t,ActivityLogRepository a,NotificationRepository nr,WorkInsightsService workInsights,@Value("${enterpriseflow.documents.storage-dir:./data/enterpriseflow-documents}") String storageDir){documents=d;meetings=m;actionItems=ai;users=u;projects=p;tasks=t;activity=a;notificationRepository=nr;this.workInsights=workInsights;storageDirectory=Paths.get(storageDir).toAbsolutePath().normalize();}
 private User user(String email){User u=users.findByEmail(email).orElseThrow();if(u.getMembershipStatus()!=MembershipStatus.ACTIVE||u.getCompany()==null)throw new AccessDeniedException("Your company access is not active.");return u;} private boolean admin(User u){return u.getRole()==UserRole.ADMIN;}
 private void projectAccess(User u,Project p){if(p!=null&&(!p.getCompany().getId().equals(u.getCompany().getId())||(!admin(u)&&!p.hasMember(u.getId()))))throw new AccessDeniedException("You do not have access to this project.");}
 private void meetingAccess(User u,Meeting m){if(!m.getOrganizer().getCompany().getId().equals(u.getCompany().getId()))throw new AccessDeniedException("You do not have access to this meeting.");if(!admin(u)&&!m.getOrganizer().getId().equals(u.getId())&&!m.getInvitees().stream().anyMatch(invitee->invitee.getId().equals(u.getId()))&&(m.getProject()==null||!m.getProject().hasMember(u.getId())))throw new AccessDeniedException("You do not have access to this meeting.");}
 private boolean canRead(User u,Document d){return !d.isArchived()&&d.getOwner().getCompany()!=null&&d.getOwner().getCompany().getId().equals(u.getCompany().getId())&&(admin(u)||"COMPANY".equals(d.getVisibility())||d.getOwner().getId().equals(u.getId())||(d.getProject()!=null&&d.getProject().hasMember(u.getId())));}
 private Map<String,Object> doc(Document d){Map<String,Object>x=new LinkedHashMap<>();x.put("id",d.getId());x.put("title",d.getTitle());x.put("fileName",d.getFileName());x.put("contentType",Objects.toString(d.getContentType(),""));x.put("visibility",d.getVisibility());x.put("projectId",d.getProject()==null?null:d.getProject().getId());x.put("owner",d.getOwner().getName());x.put("createdAt",d.getCreatedAt());return x;}
 @Transactional public Map<String,Object> upload(String email,String title,String visibility,UUID projectId,MultipartFile file)throws Exception{if(file==null||file.isEmpty())throw new IllegalArgumentException("Choose a non-empty file.");if(file.getSize()>5_000_000)throw new IllegalArgumentException("Documents must be 5 MB or smaller.");String name=Objects.requireNonNullElse(file.getOriginalFilename(),"upload"),type=Objects.requireNonNullElse(file.getContentType(),"");if(!type.startsWith("text/")&&!name.matches("(?i).*\\.(txt|md|markdown|csv)$"))throw new IllegalArgumentException("Only text, Markdown, or CSV uploads can be indexed.");String normalizedVisibility=visibility==null?"COMPANY":visibility.trim().toUpperCase(Locale.ROOT);if(!normalizedVisibility.matches("COMPANY|PROJECT|PRIVATE"))throw new IllegalArgumentException("Invalid document visibility.");User owner=user(email);Project p=projectId==null?null:projects.findById(projectId).orElseThrow(()->new NoSuchElementException("Project not found."));projectAccess(owner,p);if("PROJECT".equals(normalizedVisibility)&&p==null)throw new IllegalArgumentException("Project visibility requires a project.");Files.createDirectories(storageDirectory);Path stored=storageDirectory.resolve(UUID.randomUUID()+"-"+name.replaceAll("[^a-zA-Z0-9._-]","_")).normalize();if(!stored.startsWith(storageDirectory))throw new IllegalArgumentException("Invalid file name.");Files.copy(file.getInputStream(),stored);Document d=documents.save(new Document(title==null||title.isBlank()?name:title.trim(),name,type,stored.toString(),Files.readString(stored,StandardCharsets.UTF_8),normalizedVisibility,p,owner));activity.save(new ActivityLog(owner,"UPLOADED","DOCUMENT",d.getId(),"Uploaded document "+d.getTitle()));return doc(d);}
 @Transactional(readOnly=true) public List<Map<String,Object>> documents(String email){User u=user(email);return documents.findAll().stream().filter(d->canRead(u,d)).map(this::doc).toList();}
 @Transactional(readOnly=true) public Map<String,Object> document(String email,UUID id){User u=user(email);Document d=documents.findById(id).orElseThrow(()->new NoSuchElementException("Document not found."));if(!canRead(u,d))throw new AccessDeniedException("You do not have access to this document.");Map<String,Object> result=doc(d);result.put("text",Objects.toString(d.getExtractedText(),""));return result;}
 @Transactional(readOnly=true) public Resource download(String email,UUID id){User u=user(email);Document d=documents.findById(id).orElseThrow(()->new NoSuchElementException("Document not found."));if(!canRead(u,d))throw new AccessDeniedException("You do not have access to this document.");Path path=Paths.get(d.getStoragePath()).normalize();if(!path.startsWith(storageDirectory)||!Files.isRegularFile(path))throw new NoSuchElementException("Document file is unavailable.");return new FileSystemResource(path);}
 @Transactional(readOnly=true) public List<Map<String,Object>> search(String email,String q){if(q==null||q.isBlank())throw new IllegalArgumentException("A search query is required.");User u=user(email);return documents.search(q.trim()).stream().filter(d->canRead(u,d)).map(this::doc).toList();}
 @Transactional public void archiveDocument(String email,UUID id){User u=user(email);Document d=documents.findById(id).orElseThrow(()->new NoSuchElementException("Document not found."));if(!admin(u)&&!d.getOwner().getId().equals(u.getId()))throw new AccessDeniedException("Only the document owner or an administrator can archive it.");if(!d.getOwner().getCompany().getId().equals(u.getCompany().getId()))throw new AccessDeniedException("You do not have access to this document.");d.archive();activity.save(new ActivityLog(u,"ARCHIVED","DOCUMENT",id,"Archived document "+d.getTitle()));}
 @Transactional(readOnly=true) public Map<String,Object> ask(String email,String question){User u=user(email);if(question==null||question.isBlank())throw new IllegalArgumentException("A question is required.");if(question.length()>1000)throw new IllegalArgumentException("Questions must be 1000 characters or fewer.");if(WorkInsightsService.isWorkQuestion(question))return workInsights.answer(email,question,meetingInsightData(email));List<Document> found=documents.search(question).stream().filter(d->canRead(u,d)).limit(3).toList();if(found.isEmpty())return Map.of("answer","I could not find authorized company knowledge that answers this question.","sources",List.of());return Map.of("answer","Relevant authorized knowledge was found. Review the excerpts and sources below.","sources",found.stream().map(d->Map.of("id",d.getId(),"title",d.getTitle(),"excerpt",Objects.toString(d.getExtractedText(),"").substring(0,Math.min(Objects.toString(d.getExtractedText(),"").length(),500)))).toList());}
 private List<Map<String,Object>> meetingInsightData(String email){return meetings(email).stream().map(meeting->{Map<String,Object> data=new LinkedHashMap<>();data.put("id",meeting.get("id"));data.put("title",meeting.get("title"));data.put("scheduledAt",meeting.get("scheduledAt"));data.put("summary",meeting.get("summary"));return data;}).toList();}
 @Transactional public Map<String,Object> createMeeting(String email,MeetingRequest r){User organizer=user(email);Project p=r.projectId()==null?null:projects.findById(r.projectId()).orElseThrow(()->new NoSuchElementException("Project not found."));projectAccess(organizer,p);List<User> invitees=r.inviteeIds()==null?List.of():r.inviteeIds().stream().distinct().map(id->users.findById(id).orElseThrow(()->new NoSuchElementException("Invitee not found."))).toList();for(User invitee:invitees){if(invitee.getMembershipStatus()!=MembershipStatus.ACTIVE||invitee.getCompany()==null||!invitee.getCompany().getId().equals(organizer.getCompany().getId()))throw new IllegalArgumentException("Invitees must be active company members.");}Meeting m=meetings.save(new Meeting(r.title().trim(),p,organizer,r.scheduledAt(),r.transcript(),r.timezone(),r.externalLink(),invitees));for(User invitee:invitees)if(!invitee.getId().equals(organizer.getId())){activity.save(new ActivityLog(organizer,"INVITED","MEETING",m.getId(),"Invited "+invitee.getName()+" to "+m.getTitle()));String when=m.getScheduledAt()==null?"":(" at "+m.getScheduledAt());notificationRepository.save(new Notification(invitee,"Meeting invitation",organizer.getName()+" invited you to "+m.getTitle()+when,"MEETING_INVITATION"));}activity.save(new ActivityLog(organizer,"CREATED","MEETING",m.getId(),"Created meeting "+m.getTitle()));return meeting(m);}
 @Transactional public Map<String,Object> summarize(String email,UUID id){User u=user(email);Meeting m=meetings.findById(id).orElseThrow(()->new NoSuchElementException("Meeting not found."));meetingAccess(u,m);m.analyze();activity.save(new ActivityLog(u,"SUMMARIZED","MEETING",id,"Summarized meeting "+m.getTitle()));return meeting(m);}
 @Transactional public Map<String,Object> addActionItem(String email,UUID meetingId,ActionItemRequest r){User u=user(email);Meeting m=meetings.findById(meetingId).orElseThrow(()->new NoSuchElementException("Meeting not found."));meetingAccess(u,m);User assignee=r.assigneeId()==null?null:users.findById(r.assigneeId()).orElseThrow();if(assignee!=null&&(assignee.getMembershipStatus()!=MembershipStatus.ACTIVE||!assignee.getCompany().getId().equals(u.getCompany().getId())))throw new IllegalArgumentException("Assignee must be an approved company member.");MeetingActionItem item=actionItems.save(new MeetingActionItem(m,r.title().trim(),assignee,r.dueDate()));activity.save(new ActivityLog(u,"CREATED","MEETING_ACTION",item.getId(),"Added action item "+item.getTitle()));return action(item);}
 @Transactional public Map<String,Object> convertActionItem(String email,UUID meetingId,UUID itemId){User u=user(email);Meeting m=meetings.findById(meetingId).orElseThrow(()->new NoSuchElementException("Meeting not found."));meetingAccess(u,m);if(!admin(u)||m.getProject()==null)throw new AccessDeniedException("An administrator can convert action items only for project meetings.");MeetingActionItem item=actionItems.findById(itemId).orElseThrow(()->new NoSuchElementException("Action item not found."));if(!item.getMeeting().getId().equals(m.getId()))throw new AccessDeniedException("Action item belongs to another meeting.");if(item.getTask()!=null)throw new IllegalArgumentException("This action item has already been converted.");if(item.getAssignee()!=null&&!m.getProject().hasMember(item.getAssignee().getId()))throw new IllegalArgumentException("The action-item assignee must be added to the project before conversion.");Task t=tasks.save(new Task(m.getProject(),item.getTitle(),"Created from meeting: "+m.getTitle(),"MEDIUM",item.getAssignee(),u,item.getDueDate()));item.convert(t);activity.save(new ActivityLog(u,"CONVERTED","MEETING_ACTION",item.getId(),"Converted action item to task "+t.getTitle()));return action(item);}
 @Transactional(readOnly=true) public List<Map<String,Object>> meetings(String email){User u=user(email);return meetings.findAllByOrderByScheduledAtDesc().stream().filter(m->{try{meetingAccess(u,m);return true;}catch(AccessDeniedException e){return false;}}).map(this::meeting).toList();}
 private NotificationRepository notifications(){return notificationRepository;} private final NotificationRepository notificationRepository; private Map<String,Object> action(MeetingActionItem i){Map<String,Object>x=new LinkedHashMap<>();x.put("id",i.getId());x.put("title",i.getTitle());x.put("assignee",i.getAssignee()==null?null:i.getAssignee().getName());x.put("assigneeId",i.getAssignee()==null?null:i.getAssignee().getId());x.put("dueDate",i.getDueDate());x.put("status",i.getStatus());x.put("taskId",i.getTask()==null?null:i.getTask().getId());return x;} private Map<String,Object> meeting(Meeting m){Map<String,Object>x=new LinkedHashMap<>();x.put("id",m.getId());x.put("title",m.getTitle());x.put("projectId",m.getProject()==null?null:m.getProject().getId());x.put("scheduledAt",m.getScheduledAt());x.put("timezone",m.getTimezone());x.put("externalLink",m.getExternalLink());x.put("invitees",m.getInvitees().stream().map(User::getName).toList());x.put("transcript",m.getTranscript());x.put("summary",m.getSummary());x.put("decisions",m.getDecisions());x.put("actionItems",actionItems.findByMeetingIdOrderByCreatedAtAsc(m.getId()).stream().map(this::action).toList());return x;}
}
